// <auto-generated />
using System;
using FortiTrafficAnalysis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FortiTrafficAnalysis.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260213182703_ChangeConfigFileToVarbinary")]
    partial class ChangeConfigFileToVarbinary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AIConversation", b =>
                {
                    b.Property<Guid>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AIResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUPN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("int");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("int");

                    b.Property<Guid>("TrafficAnalysisID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConversationID");

                    b.HasIndex("CreatedByUPN");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("TrafficAnalysisID");

                    b.ToTable("AIConversations");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AppGroup", b =>
                {
                    b.Property<Guid>("AppGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppGroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AppGroupID");

                    b.HasIndex("AppGroupName")
                        .IsUnique();

                    b.ToTable("AppGroups");

                    b.HasData(
                        new
                        {
                            AppGroupID = new Guid("11111111-1111-1111-1111-111111111111"),
                            AppGroupName = "Users"
                        },
                        new
                        {
                            AppGroupID = new Guid("22222222-2222-2222-2222-222222222222"),
                            AppGroupName = "Admins"
                        });
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("AppAccessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppGroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AppUserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserUPN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AppAccessID");

                    b.HasIndex("AppGroupID");

                    b.HasIndex("UserUPN")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            AppAccessID = new Guid("33333333-3333-3333-3333-333333333333"),
                            AppGroupID = new Guid("22222222-2222-2222-2222-222222222222"),
                            AppUserEmail = "admin@fgtas.local",
                            AppUserName = "System Administrator",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            UserUPN = "admin@fgtas.local"
                        });
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerID");

                    b.HasIndex("CustomerName")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FTAService", b =>
                {
                    b.Property<Guid>("FTAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ServiceEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ServiceStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FTAID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("JobID")
                        .IsUnique();

                    b.ToTable("FTAServices");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FortiGate", b =>
                {
                    b.Property<Guid>("FGID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ConfigFileCompressed")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("ConfigUploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FGHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FGHostname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FGSerial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FGStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FGapiKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FGvDOM")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FTAID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FGID");

                    b.HasIndex("FGSerial")
                        .IsUnique();

                    b.HasIndex("FTAID");

                    b.ToTable("FortiGates");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.TrafficAnalysis", b =>
                {
                    b.Property<Guid>("TrafficAnalysisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUPN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("FGID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FTAID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TrafficAnalysisID");

                    b.HasIndex("CreatedByUPN");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("CustomerID");

                    b.HasIndex("FGID");

                    b.HasIndex("FTAID");

                    b.HasIndex("Status");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("TrafficAnalysis");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.TrafficAnalysisRecommendation", b =>
                {
                    b.Property<Guid>("TrafficAnalysisRecommendationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUPN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TrafficAnalysisID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrafficAnalysisRecommendationID");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("TrafficAnalysisID");

                    b.ToTable("TrafficAnalysisRecommendations");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.TrafficLog", b =>
                {
                    b.Property<Guid>("TrafficLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DstIP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DstInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DstPort")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<Guid?>("FGID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ImportedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("LogId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PolicyId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PolicyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Proto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RawLogLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RcvdByte")
                        .HasColumnType("bigint");

                    b.Property<long?>("SentByte")
                        .HasColumnType("bigint");

                    b.Property<string>("Service")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SrcIP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SrcInt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SrcPort")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TrafficAnalysisID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrafficLogID");

                    b.HasIndex("Action");

                    b.HasIndex("DstIP");

                    b.HasIndex("FGID");

                    b.HasIndex("LogDate");

                    b.HasIndex("SrcIP");

                    b.HasIndex("TrafficAnalysisID");

                    b.ToTable("TrafficLogs");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AIConversation", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.TrafficAnalysis", "TrafficAnalysis")
                        .WithMany()
                        .HasForeignKey("TrafficAnalysisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrafficAnalysis");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.AppGroup", "AppGroup")
                        .WithMany("AppUsers")
                        .HasForeignKey("AppGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppGroup");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FTAService", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.Customer", "Customer")
                        .WithMany("FTAServices")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FortiGate", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.FTAService", "FTAService")
                        .WithMany("FortiGates")
                        .HasForeignKey("FTAID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FTAService");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.TrafficAnalysis", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.FortiGate", "FortiGate")
                        .WithMany()
                        .HasForeignKey("FGID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.FTAService", "FTAService")
                        .WithMany()
                        .HasForeignKey("FTAID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("FTAService");

                    b.Navigation("FortiGate");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.TrafficAnalysisRecommendation", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.TrafficAnalysis", "TrafficAnalysis")
                        .WithMany("Recommendations")
                        .HasForeignKey("TrafficAnalysisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrafficAnalysis");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.TrafficLog", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.FortiGate", "FortiGate")
                        .WithMany("TrafficLogs")
                        .HasForeignKey("FGID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.TrafficAnalysis", "TrafficAnalysis")
                        .WithMany("TrafficLogs")
                        .HasForeignKey("TrafficAnalysisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FortiGate");

                    b.Navigation("TrafficAnalysis");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AppGroup", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.Customer", b =>
                {
                    b.Navigation("FTAServices");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FTAService", b =>
                {
                    b.Navigation("FortiGates");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FortiGate", b =>
                {
                    b.Navigation("TrafficLogs");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.TrafficAnalysis", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("TrafficLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
