// <auto-generated />
using System;
using FortiTrafficAnalysis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FortiTrafficAnalysis.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212031254_AddPasswordHashToAppUser")]
    partial class AddPasswordHashToAppUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AppGroup", b =>
                {
                    b.Property<Guid>("AppGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppGroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AppGroupID");

                    b.HasIndex("AppGroupName")
                        .IsUnique();

                    b.ToTable("AppGroups");

                    b.HasData(
                        new
                        {
                            AppGroupID = new Guid("11111111-1111-1111-1111-111111111111"),
                            AppGroupName = "Users"
                        },
                        new
                        {
                            AppGroupID = new Guid("22222222-2222-2222-2222-222222222222"),
                            AppGroupName = "Admins"
                        });
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("AppAccessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppGroupID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppUserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AppUserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserUPN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AppAccessID");

                    b.HasIndex("AppGroupID");

                    b.HasIndex("UserUPN")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            AppAccessID = new Guid("33333333-3333-3333-3333-333333333333"),
                            AppGroupID = new Guid("22222222-2222-2222-2222-222222222222"),
                            AppUserEmail = "admin@fgtas.local",
                            AppUserName = "System Administrator",
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            UserUPN = "admin@fgtas.local"
                        });
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerID");

                    b.HasIndex("CustomerName")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FTAService", b =>
                {
                    b.Property<Guid>("FTAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ServiceEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ServiceStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FTAID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("JobID")
                        .IsUnique();

                    b.ToTable("FTAServices");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FortiGate", b =>
                {
                    b.Property<Guid>("FGID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FGHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FGHostname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FGSerial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FGStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FGapiKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FGvDOM")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FTAID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FGID");

                    b.HasIndex("FGSerial")
                        .IsUnique();

                    b.HasIndex("FTAID");

                    b.ToTable("FortiGates");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.TrafficLog", b =>
                {
                    b.Property<Guid>("LogTempID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DestinationPort")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("FGID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LogTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RawLogLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourcePort")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("LogTempID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("DestinationIP");

                    b.HasIndex("FGID");

                    b.HasIndex("LogTimestamp");

                    b.HasIndex("PolicyAction");

                    b.HasIndex("SourceIP");

                    b.ToTable("TrafficLogs");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.AppGroup", "AppGroup")
                        .WithMany("AppUsers")
                        .HasForeignKey("AppGroupID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppGroup");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FTAService", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.Customer", "Customer")
                        .WithMany("FTAServices")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FortiGate", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.FTAService", "FTAService")
                        .WithMany("FortiGates")
                        .HasForeignKey("FTAID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FTAService");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.TrafficLog", b =>
                {
                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.Customer", "Customer")
                        .WithMany("TrafficLogs")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FortiTrafficAnalysis.Domain.Entities.FortiGate", "FortiGate")
                        .WithMany("TrafficLogs")
                        .HasForeignKey("FGID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("FortiGate");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.AppGroup", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.Customer", b =>
                {
                    b.Navigation("FTAServices");

                    b.Navigation("TrafficLogs");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FTAService", b =>
                {
                    b.Navigation("FortiGates");
                });

            modelBuilder.Entity("FortiTrafficAnalysis.Domain.Entities.FortiGate", b =>
                {
                    b.Navigation("TrafficLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
